/**
 * 0.10.0 → 0.10.1 -- Bugfix: `memory-pkg mcp-server` command now exists.
 *
 * The `.mcp.json` stanza generated by `init` invokes
 * `npx -y @sylphie-labs/memory-pkg mcp-server` — i.e. the memory-pkg bin with a
 * `mcp-server` subcommand. That subcommand didn't exist, so the MCP server
 * crashed on launch with "unknown command: mcp-server" (Claude Code reported
 * -32000 / "Failed to reconnect"). 0.10.1 adds the subcommand, so the existing
 * stanza starts working — no consumer-repo change required. This migration only
 * advances the version cursor.
 */

import type { Migration, MigrationContext, MigrationResult } from './types.js';

const migration_0_10_0_to_0_10_1: Migration = {
  from: '0.10.0',
  to: '0.10.1',
  severity: 'patch',
  description: 'Fix: add the `mcp-server` CLI subcommand so .mcp.json launches the server (was -32000)',
  notes:
    'The MCP server stanza invokes `memory-pkg mcp-server`, which previously did ' +
    'not exist (the server lived only in the memory-pkg-mcp bin). 0.10.1 adds the ' +
    'subcommand; your existing .mcp.json now launches correctly with no edit. ' +
    'Restart Claude Code to pick up the working server.',

  async apply(ctx: MigrationContext): Promise<MigrationResult> {
    return {
      managedFiles: ctx.state.managedFiles.map((f) => ({ ...f })),
      changedFiles: [],
      warnings: [],
    };
  },
};

export default migration_0_10_0_to_0_10_1;
